[versions]
agp = "8.5.0"
kotlin = "2.0.21"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
activityVersion = "1.12.0"

[libraries]
androidx-core-ktx = { group="androidx.core", name="core-ktx", version.ref="coreKtx" }
androidx-appcompat = { group="androidx.appcompat", name="appcompat", version.ref="appcompat" }
material = { group="com.google.android.material", name="material", version.ref="material" }
androidx-constraintlayout = { group="androidx.constraintlayout", name="constraintlayout", version.ref="constraintlayout" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }

[plugins]
android-application = { id="com.android.application", version.ref="agp" }
kotlin-android = { id="org.jetbrains.kotlin.android", version.ref="kotlin" }
kotlin-kapt = { id="org.jetbrains.kotlin.kapt", version.ref="kotlin" }